### ISSUE TITLE
Update certification problem

### ISSUE THREAD

**Issue by In139** [NeoApplications/Neo-Store#619] opened 2024-05-23 23:47 UTC
I have Neo Store installed as the only app store on my phone (Pixel 7a with GrapheneOS Android 14). I downloaded and installed version 0.9.15 from here last year. Now I can't update the Neo Store from within the app. Not only does Neo Store not offer me an update, but when I start the update manually, I also get the following error message: "This version is signed with a different certificate than the version already installed. Uninstall it first." (analogously from German)

Now, if I uninstall the old version, I would no longer have an app to install the new one! So it would be the same again with the next update. Could you please fix the certification problem with the update? Thank you.
![IMG_20240524_014056](https://github.com/NeoApplications/Neo-Store/assets/102912715/313ee63f-dc86-403f-b27e-8bb387f50ddf)
![Screenshot_20240524-004959](https://github.com/NeoApplications/Neo-Store/assets/102912715/e71de76d-1ca8-4645-8b7a-bacc2fed1eee)

**Comment by machiav3lli** [comment] 2024-05-24 07:21
I guess NS falls back to http as the setup okhttp client allows it. I'll see if I'd add an option to enforce https

**Comment by machiav3lli** [comment] 2024-05-24 07:29
Can it be a duplicate of #614 , cause the certificate didn't change on my side + It's the f-droid build here in question, so it would be on their side 😅

**Comment by In139** [comment] 2024-05-24 13:02
I'm not sure about that. With the issue #614 seems to be downloading the app, albeit incorrectly. With the error I reported, the posted error message appears immediately after manually triggering an update. What was done to fix the error:
1. cleared the cache,
3. checked the battery optimization or the ability to run the app in the background,
3. checked the installer - the default session installer is selected

The initial installation was done from here (Github) as written. With Neo Store, the error message appears when trying to update (F-Droid source). 
Maybe F-Droid uses a different certificate?

**Comment by machiav3lli** [comment] 2024-05-24 13:44
Ah, now I get it, you have to activate IzzyOnDroid to get my builds (same signature as GH). F-droid official build and sign their own.

**Closed** 2024-05-24 13:45 UTC

**Comment by In139** [comment] 2024-05-24 15:30
Oh, that's not obvious to "normal" users. That was the first update I receive from g1 and it didn't work on its own. Sorry for the problem report - and the poor intelligibility due to my rudimentary English! Thanks for taking care!!!

**Comment by machiav3lli** [comment] 2024-05-27 07:06
Hehe, no issue at all. I had the assumption that you kept IzzyOnDroid active (it's active by default), but after looking at the screenshot, the builds were missing, so yeah.
