### ISSUE TITLE
UI broken on android 14

### ISSUE THREAD

**Issue by Doc-4** [NeoApplications/Neo-Store#543] opened 2023-11-18 01:29 UTC
I have the same app version on a oneplus running the last android 11 version, and a pixel running the latest grapheneOS on android 14. 

The android 11 one seems to work fine, but the pixel has the add repository and qr code buttons inside each other, and the flyout menu you get when you hold on a repo only flies out far enough to see the top half with no way to access the edit and delete buttons. More may be broken, but that's what I noticed.

**Comment by machiav3lli** [comment] 2024-04-23 20:04
The issue was really random depending on device and caused by jetpack compose. THis is now fixed in 1.0.0

**Closed** 2024-04-23 20:03 UTC
