### ISSUE TITLE
Startup and loading time for 0.9.0-rc1 is noticeable

### ISSUE THREAD

**Issue by jcperil** [NeoApplications/Neo-Store#237] opened 2022-07-03 13:19 UTC
The first thing every user notices is the app’s startup time. The last F-Droid build 0.4.3 started in no time. Version 0.9.0-rc1 startup time is at least 2-3 seconds.

Similarly, after launching the app, when you tap on Explore tab for the first time, it takes at least 2-3 seconds to show any content.

So if possible, you should display some content as soon as possible and delay the background checks and optimizations a bit.

**Comment by Offerel** [comment] 2023-01-16 16:36
Are you sure that this solved? Here with version 0.9.12 i have for 2-3 seconds the text "List loading" after starting the app. 

Also searching for a keyword seems to be slow, when you search for a second or third time. But I should create a new issue for this special use case. In the meantime, can you please check if the 2-3 seconds loading time is a expected behavior?

**Comment by jcperil** [comment] 2023-01-16 18:46
I think when I closed this, I was upset. This was not a feature request. I believed it was good feedback for improving the app. But I received no acknowledgement from the developers or fellow users of this issue. It felt like I was the only one facing this. Since you are facing similar issue, I reopened it. Cheers!

**Comment by Offerel** [comment] 2023-01-18 17:35
Many thx. Hopefully this can be fixed.

**Comment by Primokorn** [comment] 2023-02-17 15:32
I also have the problem (if another feeback was necessary) :)
I usually just subscribed to the issue instead of posting.

**Comment by K4zoku** [comment] 2023-06-28 04:08
It's 30s for me. So, I set default tab to `Installed` to temporary feel the app is nice and smooth

**Comment by machiav3lli** [comment] 2023-11-07 17:35
Already fixed in 1.0.0-alphaX

**Closed by machiav3lli** 2023-11-07 17:35 UTC
