### ISSUE TITLE
[Bug] Frequent crashes

### ISSUE THREAD

**Issue by parasiteoflife** [NeoApplications/Neo-Store#625] opened 2024-05-30 14:59 UTC
**Describe the bug**
Often the app crashes without a clear pattern, at least to me. I can be brwosing new apps, searching, installing, refreshing repositories, and it will crash.

**To Reproduce**
I'm not exactly sure. But it is happening constantly on search, or after installing one app and continuing brwosing the search results.

**Expected behavior**
Not to crash.

**Relevant information:**

- Device: Mi A3
- Android Version: 14
- ROM: LineageOS
- App's Version: 1.0.2
- Disabled battery optimization for Neo Store? Yes
- What is your selected installer? Root

-----------------------------

**Additional Notes**
This is the latest crash log:

```
FATAL EXCEPTION: WM.task-3
Process: com.machiav3lli.fdroid, PID: 23028
java.lang.OutOfMemoryError: Failed to allocate a 1296 byte allocation with 1347656 free bytes and 1316KB until OOM, target footprint 201326592, growth limit 201326592; giving up on allocation because <1% of heap free after GC.
	at java.lang.StringFactory.newStringFromBytes(Native Method)
	at java.lang.StringLatin1.newString(StringLatin1.java:738)
	at java.lang.StringBuilder.toString(StringBuilder.java:474)
	at androidx.work.impl.utils.WorkProgressUpdater$1.run(SourceFile:131)
	at androidx.work.Worker$2.run(SourceFile:280)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

This is from 14th May:

```
FATAL EXCEPTION: DefaultDispatcher-worker-18
Process: com.machiav3lli.fdroid, PID: 8757
java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 3188632 free bytes and 3113KB until OOM, target footprint 201326592, growth limit 201326592; failed due to fragmentation (largest possible contiguous allocation 0 bytes). Number of 256KB sized free regions are: 0. Likely cause: (1) Too much memory in use, and (2) many threads or many larger objects of the wrong kind
	at com.machiav3lli.fdroid.network.Downloader$download$2$1$5$1.invokeSuspend(SourceFile:30)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at androidx.work.Worker$2.run(SourceFile:27)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:96)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@19e5a65, Dispatchers.IO]
```

**Comment by machiav3lli** [comment] 2024-05-31 22:54
What (generally) and how many repos are active?

**Comment by machiav3lli** [comment] 2024-06-01 07:06
Your list is almost identical to mine, so a first would be that this is a duplicate of #599, can you please try to confirm?

**Closed as not planned** 2024-06-02 23:24 UTC

**Comment by jvschiavo** [comment] 2025-04-21 06:43
Do you still have this problem? If so, take a look at https://github.com/NeoApplications/Neo-Store/issues/728.
