### ISSUE TITLE
app won't function without permission for notification and battery opt exempton

### ISSUE THREAD

**Issue by ericjs** [NeoApplications/Neo-Store#538] opened 2023-11-05 02:15 UTC
Unless I give it the permission for notifications and exempt it from battery optimization, the app only shows me a screen asking for those, I cannot at all use the app.

**Comment by machiav3lli** [comment] 2023-11-07 17:31
Duplicate of #440 #457

**Closed by machiav3lli** 2023-11-07 17:31 UTC

**Comment by ericjs** [comment] 2023-11-07 20:19
Thanks, and sorry for the duplicate!
