### ISSUE TITLE
battery optimization forced on

### ISSUE THREAD

**Issue by rudolfmu** [NeoApplications/Neo-Store#562] opened 2024-01-27 13:16 UTC
When I first start the app I receive a popup asking to turn off Battery Optimization and allow app to always run in background. If I choose to keep the optimization the app doesn't run/continue, it is stuck in the choice popup.
I want to use Neo in manual poll mode only, no background running.

**Comment by machiav3lli** [comment] 2024-01-27 13:30
Duplicate of #440 #457 #538

For future issues, please search existing and closed issues for similar ones, before opening new one.

**Closed by machiav3lli** 2024-01-27 13:30 UTC
