### ISSUE TITLE
[Enhancement] Add a option to store/bookmark apps

### ISSUE THREAD

**Issue by Tobias-Lauerbach** [NeoApplications/Neo-Store#206] opened 2022-04-20 20:35 UTC
# Add a option to store/bookmark apps
It would be greate if it would be able of memorize apps so you can remember them before download (to compare similar ones for example). 

AuroraDroid has a simulate feature called favorite's (or the whishlist in the googleplay-store) but the latest version is older then one year and has many bugs, that's why I think it would be a great supplement to this beautiful app.

**Comment by machiav3lli** [comment] 2022-04-21 08:38
Duplicate of #21.
Otherwise, the favorite button's frontend is already there in the alphas, but still without a backend. It should be implemented till the stable release

**Closed by machiav3lli** 2022-04-21 08:38 UTC
