### ISSUE TITLE
Categories show in vertical instead of horizontal

### ISSUE THREAD

**Issue by victorfernandesraton** [NeoApplications/Neo-Store#540] opened 2023-11-07 18:59 UTC
When i open Neostore, category  filter show in vertical instead of horizontal

![Screenshot_20231107_155356_Neo Store.jpg](https://github.com/NeoApplications/Neo-Store/assets/43411882/28aa6615-0b45-4a18-9a24-40e36d92c6ed)

Device info:

Sansung Galaxy A34 5G (SM-A346M/DSN

Android version: 13

PS: i use big fonts as default

**Comment by machiav3lli** [comment] 2023-11-07 22:35
Duplicate of #515 #502

**Closed by machiav3lli** 2023-11-07 22:35 UTC
